/**********************************************************************
*
*   Types file generated by Quest
*
*   Types for the components props go in this file
*   To set up custom types for the components props, edit the corresponding types in this file
*   Once you edit a type to no longer by "any", be careful to not override it on your next export 
*   Verify diff before merging
*
*   For help and further details refer to: 
*   https://docs.quest.ai/react/fundamentals/exporting-code
*
*
**********************************************************************/

























export interface RatedProps {
  className?: any;
  rated: any;
};

























export interface GenreProps {
  className?: any;
  genre: any;
  genres: any;
};

























export interface MovieNavbarProps {
  className?: any;
  size: any;
};

























export interface TabMobileBtn2Props {
  className?: any;
};

























export interface TabDesktopBtn2Props {
  className?: any;
};

























export interface TabMobileBtn1Props {
  className?: any;
};

























export interface LanguageProps {
  className?: any;
  language: any;
};

























export interface MovieCardProps {
  className?: any;
  image: any;
};

























export interface MovieFooterProps {
  className?: any;
  size: any;
};

























export interface MovieDetailsPageProps {
  className?: any;
  isLoading: any;
};

























export interface TabDesktopBtn1Props {
  className?: any;
};

