/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { TabDesktopBtn2Props } from 'types';

 
const MouseOff: any = styled("div")({  
  backgroundColor: `rgba(0, 0, 0, 0.45)`,  
  border: `2px solid rgba(255, 255, 255, 0.7)`,  
  boxSizing: `border-box`,  
  borderRadius: `0px 50px 50px 0px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `10px 26px`,  
  width: "100vw",  
});
  
const Genre: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  margin: `0px`,  
});
 
function TabDesktopBtn2(props: TabDesktopBtn2Props): JSX.Element {
  return (
    <MouseOff  className={props.className}   >
      <Genre >
        {`Movie Details`}
          </Genre>
    </MouseOff>
  );
}

export default TabDesktopBtn2;
